experiment_name: Image_Classification
save_dir: checkpoints
seed: 42
resume_checkpoint: null
# reference_supported_arch: # check tf_train/model/models_info.py
# - Facenet, Densenet121
# - InceptionResNetV2, InceptionV3, Xception
# - EfficientNetB0, EfficientNetB2, EfficientNetB4, EfficientNetB6
# - EfficientNetV2B0, EfficientNetV2B1, EfficientNetV2B2, EfficientNetV2B3
# - EfficientNetV2S, EfficientNetV2M, EfficientNetV2L
# - MobileNetV2, MobileNetV3Large, MobileNetV3Small
arch: MobileNetV3Large
mixed_precision_global_policy: mixed_float16
trainable_feat_backbone: true

trainer:
  epochs: 10
  verbosity: auto
  val_freq: 1
  initial_epoch: 0
  num_workers: 8
  use_multiproc: true
  use_tensorboard: true
  ckpt_fmt: e{epoch:03d}_ta{accuracy:.2f}_tl{loss:.2f}_va{val_accuracy:.2f}_vl{val_loss:.2f}

data:
  train_data_dir: data/tfrecord_dataset/train/
  val_data_dir: data/tfrecord_dataset/test/
  test_data_dir: data/CIFAR-10-images/test
  train_bsize: 32
  val_bsize: 32
  test_bsize: 32
  class_map_txt_path: data/dataset_classmap.txt
  tfrecord_parallel_read: 20
  shuffle: true
  num_classes: 10
  num_train_samples: null
  num_val_samples: null

optimizer:
  type: SGD
  args:
    learning_rate: 0.01
    weight_decay: 1.0e-06
    momentum: 0.9
    nesterov: false

loss:
  categorical_crossentropy:
    type: CategoricalCrossentropy
    args:
      label_smoothing: 0.0

loss_weights:
- 1.0

callbacks:
  tensorboard_callback:
    type: LRTensorBoard
    args:
      write_images: false
      histogram_freq: 0
      profile_batch: 0
      write_graph: false
      update_freq: epoch
      embeddings_freq: 0
      embeddings_metadata: null
  ckpt_callback:
    type: ModelCheckpoint
    args:
      monitor: val_loss
      save_freq: epoch
      verbose: 0
      save_best_only: true
      save_weights_only: false
      mode: auto
  lr_reduce_callback:
    type: ReduceLROnPlateau
    args:
      monitor: val_loss
      factor: 0.1
      patience: 5
      verbose: 1
      mode: auto
      min_delta: 0.001
      cooldown: 0
      min_lr: 0
  early_stopping_callback:
    type: EarlyStopping
    args:
      monitor: val_loss
      patience: 4
      mode: auto
      min_delta: 0
      verbose: 0
      baseline: null
      restore_best_weights: false
  epoch_log_lambda_callback:
    type: LambdaCallback
    args: {}
  update_initial_epoch_callback:
    type: LambdaCallback
    args: {}

train_metrics:
  accuracy:
    type: CategoricalAccuracy
    args:
      name: accuracy

test_metrics:
  accuracy:
    type: accuracy
    args: {}
  accuracy_top_2:
    type: top_k_acc
    args:
      k: 2
  accuracy_top_3:
    type: top_k_acc
    args:
      k: 3
  acc_per_class:
    type: acc_per_class
    args: {}
  precision:
    type: precision
    args:
      average: weighted
  recall:
    type: recall
    args:
      average: weighted
  f1score:
    type: f1score
    args:
      average: weighted
  plot_confusion_matrix:
    type: plot_confusion_matrix
    args: {}

optimization:
  cluster:
    use_clustering: false
    cluster_layers: false
    is_model_already_clustered: false
    num_clusters: 4
    CentroidInitialization: clustering.keras.CentroidInitialization.DENSITY_BASED
    cluster_layer_names:
    - conv2d_1
  quantize:
    use_quantization: false
    during_training_quantization: false
    quantize_layers: false
    post_training_quantization: false
    is_model_already_quantized: false
    quantize_layer_names:
    - conv2d_1
  prune:
    use_pruning: false
    prune_layers: false
    is_model_already_pruned: false
    prune_layer_names:
    - conv2d_1
