name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1 git

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --all-groups

      - name: Prepare .env
        run: |
          cp .env.example .env

      - name: Download CIFAR-10 images
        run: |
          mkdir -p data
          git clone --depth 1 git@github.com:YoongiKim/CIFAR-10-images.git data/CIFAR-10-images

      - name: Convert CIFAR-10 to TFRecord
        run: |
          mkdir -p data/tfrecord_dataset/train data/tfrecord_dataset/test
          poetry run python data_preparation/convert_imgs_to_tfrecord.py \
            --sd data/CIFAR-10-images/train --td data/tfrecord_dataset/train
          poetry run python data_preparation/convert_imgs_to_tfrecord.py \
            --sd data/CIFAR-10-images/test --td data/tfrecord_dataset/test

      - name: Run integration tests
        run: |
          poetry run pytest -v --maxfail=1 --disable-warnings
